# Generated by Django 6.0.4 on 2026-05-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastName',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='qb_id',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
