# Generated by Django 6.0.4 on 2026-05-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_customer_firstname_remove_customer_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
