# Generated by Django 6.0.4 on 2026-05-05 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemWidth', models.DecimalField(decimal_places=2, max_digits=6)),
                ('itemHeight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('itemDepth', models.DecimalField(decimal_places=2, max_digits=6)),
                ('itemDescription', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deliveryDate', models.DateTimeField(null=True)),
                ('eventDateStart', models.DateTimeField(null=True)),
                ('eventDateEnd', models.DateTimeField(null=True)),
                ('pickupDate', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('notes', models.CharField(max_length=500, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rental')),
            ],
        ),
    ]
