# Generated by Django 6.0.4 on 2026-05-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_item_rental_rentalitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='price',
        ),
        migrations.AddField(
            model_name='rental',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='None', max_length=254),
        ),
    ]
