# Generated by Django 6.0.4 on 2026-05-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachlog',
            name='lastContacted',
            field=models.DateTimeField(),
        ),
    ]
