# Generated by Django 6.0.4 on 2026-06-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_outreachlog_lastcontacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sms_consent',
            field=models.BooleanField(default=False),
        ),
    ]
