# Generated by Django 6.0.4 on 2026-06-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_customer_sms_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbID', models.BigIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('deliveryDate', models.DateTimeField(null=True)),
                ('eventDateStart', models.DateTimeField(null=True)),
                ('eventDateEnd', models.DateTimeField(null=True)),
                ('pickupDate', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('notes', models.CharField(max_length=500, null=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estimate')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbID', models.BigIntegerField()),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rental')),
            ],
        ),
    ]
