# Generated by Django 6.0.4 on 2026-06-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_estimate_estimateitem_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
