# Generated by Django 6.0.4 on 2026-06-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_estimate_isaccepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qb_id',
            field=models.IntegerField(default=1),
        ),
    ]
