# Generated by Django 6.0.4 on 2026-06-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_item_qb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='qbID',
            new_name='qb_id',
        ),
    ]
