# Generated by Django 6.0.4 on 2026-06-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rename_qbid_estimate_qb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='invoice_qb_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
