# Generated by Django 6.0.4 on 2026-06-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_estimate_invoice_qb_id_delete_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='invoice_qb_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
