# Generated by Django 6.0.4 on 2026-06-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_estimate_invoice_qb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
