# Generated by Django 6.0.4 on 2026-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_item_taxable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='qb_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
